# Generated by Django 4.0.1 on 2022-01-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planenumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airportname', models.CharField(choices=[('Far away airport', 'Far away airport'), ('Close airport', 'Close airport'), ('Strange airport', 'Strange airport'), ('World Pain airport', 'World Pain airport'), ('Miami airport', 'Miami airport'), ('Moscow airport', 'Moscow airport')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(choices=[('11 SEPTEMBER COMPANY', '11 SEPTEMBER COMPANY'), ('ALIBABA Inc', 'ALIBABA Inc'), ('AIR BOMB Corp.', 'AIR BOMB Corp.'), ('We will die Inc', 'We will die Inc')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('1B', '1B'), ('2B', '2B'), ('1C', '1C'), ('2C', '2C'), ('1D', '1D'), ('2D', '2D'), ('1E', '1E'), ('2E', '2E')], max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaceNumber', models.CharField(max_length=30)),
                ('From', models.CharField(choices=[('This airport', 'This airport')], max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airport')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='Race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.flightrace'),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airplane'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.company'),
        ),
    ]
